name: interactive-sample
version: '0.1.0'
category: Web
author: maton
maintainer: automatonix@gmail.com
copyright: 2018 Yokoyama Haruki
license: BSD3
github: matonix/interactive-sample

source-dirs: src
dependencies:
- base >=4.7 && <5
- optparse-generic
- yaml
- reflection
- data-default
ghc-options:
- -Wall
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  interactive-sample:
    main: Main.hs
    source-dirs: app

tests:
  interactive-sample-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - interactive-sample
    - hspec
